.catalog:
  name: CICD
    # Name of the versioned template of the Catalog Entry
  version: 4.0.0
    # Version of the versioned template of the Catalog Entry
  description: rancher compose desc
    # Description of the versioned template of the Catalog Entry
  upgrade_from: "<=3.0.0"
    # The previous versions that this template can be upgraded from
  questions:
    - variable: "JENKINS_PORT"
      type: "int"
      required: true
      default: 8081
      label: "Jenkins Public Port"
      description: "Jenkins Public Port"
    - variable: "JENKINS_SLAVEPORT"
      type: "int"
      default: 50000
      required: true
      label: "Jenkins Slave Port"
      description: "Public Port"
    - variable: "VOLUME_DIR"
      default: /var/jenkins_home
      type: "string"
      label: "Jenkins Home Volume"
      description: "***:/var/jenkins_home"
    - variable: "HOST_NAME"
      required: true
      type: "string"
      label: "Webhook URL"
      description: "Used for accept github webhook"
    - variable: "WEBHOOK_PORT"
      type: "int"
      required: true
      label: "Webhook Public Port"
      default: 8084
      description: "Used for webhook public port"
pipeline-lb:
  scale: 1
  lb_config:
    port_rules:
    - source_port: 80
      target_port: 60081
      service: pipeline-server
      # hostname
      # path
