name: CICD_UI # Name of the Catalog Entry
description: UI_DEV
  # Description of the Catalog Entry
version: 8fb82bc # Version of the Catalog to be used
category: Infra # Category to be used for searching catalog entries
maintainer: Aaron # The maintainer of the catalog entry
license: MIT # The license