name: CICD_UI_DEV # Name of the Catalog Entry
description: UI_DEV
  # Description of the Catalog Entry
version: v0.1.0 # Version of the Catalog to be used
category: Infra # Category to be used for searching catalog entries
maintainer: Aaron # The maintainer of the catalog entry
license: MIT # The license