version: '2'
services:
  jenkins-data-volume:
    image: busybox
    command: /bin/true
    labels:
      io.rancher.container.start_once: 'true'
    volumes:
      - /var/jenkins_home
    entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
  jenkins-master:
    image: jenkinsci/jenkins:lts
    ports:
      - ${JENKINS_PORT}:8080
      - ${JENKINS_SLAVEPORT}:50000
    restart: always
    environment:
      - JENKINS_SLAVE_AGENT_PORT=50000
      - JENKINS_HOME=/var/jenkins_home
    volumes:
      - /usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - jenkins-data-volume
    labels:
      io.rancher.sidekicks: jenkins-data-volume
  jenkins-slave:
    image:  rancher/jenkins-slave:latest
    restart: always
    depends_on: [ jenkins-master ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - jenkins-data-volume
    environment:
      - JENKINS_USERNAME=root
      - JENKINS_PASSWORD=Rancher123
      - JENKINS_MASTER=jenkins-master:50000
  pipeline-server:
    image: lawr/pipeline:5054
    restart: always
    depends_on: [ jenkins-master ]
    environment:
      - JENKINS_USERNAME=root
      - JENKINS_PASSWORD=Rancher123
      - CATTLE_UR=http://47.52.64.92:8080/v2
      - JENKINS_ADDRESS=http://47.52.64.92:8081
      - CATTLE_ACCESS_KEY=B18A14F54899D6D4ADF2
      - CATTLE_SECRET_KEY=2RTNfZMGGAMHC6UBPmaDdyWuywFovSvzHh4MKPsy