jenkins-master:
  image: jenkinsci/jenkins:lts
  ports:
    - ${JENKINS_PORT}:8080
    - ${JENKINS_SLAVEPORT}:50000
  restart: always
  environment:
    - JENKINS_SLAVE_AGENT_PORT=50000
    - JENKINS_HOME=/var/jenkins_home
