jenkins-master:
  image: jenkinsci/jenkins:lts
  ports:
    - ${JENKINS_PORT}:8080
    - ${JENKINS_SLAVEPORT}:50000
  restart: always
  environment:
    - JENKINS_SLAVE_AGENT_PORT=50000
    - JENKINS_HOME=/var/jenkins_home
  volumes:
    - /var/jenkins_home
jenkins-slave:
  image: rancher/jenkins-slave
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - jenkins-master
  environment:
    - JENKINS_USERNAME=root
    - JENKINS_PASSWORD=Rancher123
    - JENKINS_MASTER=http://jenkins-master:8080
pipeline-server:
  image: lawr/pipeline:5054
  restart: always
  links:
    - jenkins-master
  environment:
    - JENKINS_ADDRESS=http://jenkins-master:8080
    - JENKINS_USERNAME=root
    - JENKINS_PASSWORD=Rancher123
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
