jenkins-master:
  image: reg.cnrancher.com/pipeline/jenkins:2.60.2
  ports:
    - ${JENKINS_PORT}:8080
    - ${JENKINS_SLAVEPORT}:50000
  restart: always
  environment:
    - JENKINS_SLAVE_AGENT_PORT=50000
    - JENKINS_HOME=/var/jenkins_home
  volumes_from:
    - jenkins-boot
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
    io.rancher.sidekicks: jenkins-boot
jenkins-boot:
  image: reg.cnrancher.com/pipeline/jenkins_home:2.60.2
  volumes:
    - ${volume_work}:/var/jenkins_home/workspace
  labels:
    io.rancher.container.start_once: true

pipeline-server:
  image: lawr/pipeline:5054
  links:
    - jenkins-master
  environment:
    - JENKINS_ADDRESS=http://jenkins-master:8080
    - JENKINS_USER=admin
    - JENKINS_TOKEN=admin
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
