jenkins-master:
  image: jenkins/jenkins:2.60.2
  ports:
    - ${JENKINS_PORT}:8080
    - ${JENKINS_SLAVEPORT}:50000
  restart: always
  environment:
    - JENKINS_SLAVE_AGENT_PORT=50000
    - JENKINS_HOME=/var/jenkins_home
  volumes_from:
    - jenkins-boot
  labels:
    io.rancher.sidekicks: jenkins-boot
jenkins-boot:
  image: reg.cnrancher.com/pipeline/jenkins_home:2.60.2
  volumes:
    - /var/jenkins_home
  volumes:
    - ${volume_work}:/var/jenkins_home
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "jenkins:jenkins", "/var/jenkins_home"]

# pipeline-server:
#   image: lawr/pipeline:5054
#   restart: always
#   links:
#     - jenkins-master
#   environment:
#     - JENKINS_ADDRESS=http://jenkins-master:8080
#     - JENKINS_USERNAME=root
#     - JENKINS_PASSWORD=Rancher123
#   labels:
#     io.rancher.container.create_agent: true
#     io.rancher.container.agent.role: environment
