.catalog:
  name: ui_v2-cicd
    # Name of the versioned template of the Catalog Entry
  version: v0.1.7
    # Version of the versioned template of the Catalog Entry
  description: rancher compose desc
    # The previous versions that this template can be upgraded from
  questions:
    - variable: "PORT"
      default: 8083
      type: "int"
      required: true
      label: "Port"
      description: "Public Port"
    - variable: "RANCHER"
      type: "string"
      required: true
      label: "RANCHER"
      description: "Rancher server URL"
      default: "http://47.52.106.231:8080/"
